name = "my-dsa-hub"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 (recommended for in-app editing + search)
[[d1_databases]]
binding = "DB"
database_name = "my-dsa-gallery"
database_id = "2947afb4-1063-4999-a9bb-223e23c3281a"
migrations_dir = "migrations"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
