-- Add auto-incrementing ID column to problems table
ALTER TABLE problems ADD COLUMN id INTEGER;

-- Populate IDs using rowid as base (rowid is auto-generated by SQLite)
UPDATE problems SET id = (SELECT COUNT(*) FROM problems WHERE rowid <= problems.rowid);

-- Create index on the new id column
CREATE INDEX IF NOT EXISTS idx_problems_id ON problems(id);

-- Add index for created_at for better sorting performance
CREATE INDEX IF NOT EXISTS idx_problems_created ON problems(created_at);